### ISSUE TITLE
minimp3 test against sine.mp3 fails

### ISSUE THREAD

**Issue by hdt551** [lieff/minimp3#21]
Running the minimp3 test against a sine wave mp3 generated with Audacity fails with:
rate=44100 samples=0 max_diff=0 PSNR=99.000000
error: mp4 test should decode some samples

The generated sine wave plays without issue on other players.  
Using latest commit: 7b2bb87289d2aed534bc6b1cc5146ce7bb29681f
I hope I am not missing something obvious here.

**Comment by lieff** [comment]
Hi, thanks for the issue)
I can reproduce the problem, I will look at it ASAP.

**Comment by lieff** [comment]
Fixed in https://github.com/lieff/minimp3/commit/c9dc576c3a5d46f5ea2dfbfe59f514b11c75e05b
Now both stream and -DMP4_MODE modes shows correct decoded number of samples:
```
$ ./minimp3 audacity.mp3
rate=44100 samples=1325952 max_diff=0 PSNR=99.000000
```
For correct PSNR calculation you must provide reference file (probably from some other decoder).
To only decode to wav file, you can skip reference file and provide output file:
```
$ ./minimp3 audacity.mp3 - audacity.wav
```

**Comment by hdt551** [comment]
Thank you.
