### ISSUE TITLE
Process mp3 file in small buffer segments

### ISSUE THREAD

**Issue by hdt551** [lieff/minimp3#23]
Hi lieff,

I am trying to use your decoder on an embedded microcontroller.
That means I must process the mp3 file in small increments. I am
currently using a 4096 buffer. The difficulty I believe is when the
beginning of one frame is in the current buffer and the rest of it
is in the yet-to-be-read file.  I should be able to do this by
moving the unprocessed data from the current buffer and combining
it with new data when I refill the buffer.

Specific example I am working on:
first buffer (4096 bytes), does not contain a valid frame and 
the result of:
     samples=mp3dec_decode_frame(&mp3d, readPtr, g_bytesLeftInBuffer, g_pcmFromMp3Decoder,&info)
is:
     samples=0, info.frame_bytes=4092
at this point I:
		if (samples==0 && info.frame_bytes>0 && (g_bytesLeftInBuffer-info.frame_bytes==4)) {
			readPtr += info.frame_bytes;
			g_bytesLeftInBuffer-=info.frame_bytes;
			memmove(g_fileReadBuffer, readPtr, g_bytesLeftInBuffer);
			bytesActuallyGotten=fread(g_fileReadBuffer+g_bytesLeftInBuffer,1,FILE_READ_BUFFER_SIZE - g_bytesLeftInBuffer,f_ptr); // fill the buffer again
			readPtr=g_fileReadBuffer;
			g_bytesLeftInBuffer=g_bytesLeftInBuffer + bytesActuallyGotten;
		}

the next run of:
     samples=mp3dec_decode_frame(&mp3d, readPtr, g_bytesLeftInBuffer, g_pcmFromMp3Decoder,&info)
gives me:
     samples=1152, info.frame_bytes=666
I then do:
			readPtr += info.frame_bytes;
			g_bytesLeftInBuffer-=info.frame_bytes;
and will continue to work fine until I near the end of the 4096 bytes.
At the point when g_bytesLeftInBuffer=295
     samples=0, info.frame_bytes=291
Then I do this to move the unprocessed data back to the beginning of the 
g_fileReadbuffer and then fill it back up with data:
			readPtr += info.frame_bytes;
			g_bytesLeftInBuffer-=info.frame_bytes;
			memmove(g_fileReadBuffer, readPtr, g_bytesLeftInBuffer);
			bytesActuallyGotten=fread(g_fileReadBuffer+g_bytesLeftInBuffer,1,FILE_READ_BUFFER_SIZE - g_bytesLeftInBuffer,f_ptr);
			readPtr=g_fileReadBuffer;
			g_bytesLeftInBuffer=g_bytesLeftInBuffer + bytesActuallyGotten;

At this point, running:
     samples=mp3dec_decode_frame(&mp3d, readPtr, g_bytesLeftInBuffer, g_pcmFromMp3Decoder,&info)
no longer works.
and for instance
     samples=0, info.frame_bytes=963

Which I suppose is because I have messed up the memmove() and fread().

I cannot seem to tell where the next start-of-frame is to know what to memmove()
back to the beginning of g_fileReadBuffer for the next buffer read. I think this
is because I have the beginning of a frame towards the end of my buffer and the
rest of the frame will be in the next read.  Of course I want to move the unprocessed
part of the frame into the next buffer read and then finish filling it with new data
.

It looks like information from info.frame_bytes or mp3d_find_frame()
doesn't necessarily tell you where the start of frame is? 
Also very possible I am simply not using it correctly.

Thanks for any suggestions.

**Comment by lieff** [comment]
There reason why buffer that holds one frame must be provided by application.

If decoder can receive buffers of any size (i.e. streaming). Decoder must combine mp3 frame internally. 

It means ~16kb fixed buffer must be used (to achieve good sync procedure with MAX_FRAME_SYNC_MATCHES=10), or use malloc/realloc to allocate as needed.

So if we want smallest decoder as possible, and do not want use malloc, we must pass task of providing at least one frame to application, because application may not want MAX_FRAME_SYNC_MATCHES=10, mp4 mode do not need this combine buffer at all (all frames already packed in packets).

Maximum frame size for mp3 is 1441 bytes (2881 for mp2). So you must keep g_bytesLeftInBuffer at least ~3kb before decoder call. Also you must skip ID3 tags, to be in low memory footprint, you can skip parts and check that mp3 frame is found using mp3d_find_frame (see MP4_MODE example in minimp3_test.c).

**Comment by hdt551** [comment]
I increased the size of my file buffer and added code to make sure at least 3k bytes are available before calling decoder and it is working now.

Thank you for your help.

**Comment by hdt551** [comment]
I appreciate the suggestion.

Thanks.

**Comment by lieff** [comment]
Yes, unfortunately I do not keep mp3 on which I face this problem using amp decoder to make a closer look. Anyway, skipping id3 should be easy task, id3v2 skip already implemented in test https://github.com/lieff/minimp3/blob/master/minimp3_test.c#L70
