### ISSUE TITLE
Fix conversion warnings

### ISSUE THREAD

**Issue by djphoenix** [lieff/minimp3#37]
Please fix all of `-Wconversion` warnings in minimp3 code. Most of them are non-critical, but fixing them is a way to robust stable code.

**Comment by lieff** [comment]
Hmm, I think Wextra enables all warnings. Thanks for catching, I will fix it later.

**Comment by lieff** [comment]
I've make a try to fix this, but I do not like the result. Since code heavily rely on signed comparison and then values copied to unsigned back and forth, fixing this warnings makes code bigger and less readable.
Taking into account that warnings is not enabled with -Wextra and code is valid, is there some good reasons in fixing this?

**Comment by djphoenix** [comment]
Are there a real reason to convert signed to unsigned and back for many times? Somewhere I think variables may be changed to single variant without explicit conversion and it should be more readable than now...

**Comment by lieff** [comment]
Yes, actually there lot of places where it converted for reason. For example:
```
    uint32_t next, cache = 0, s = bs->pos & 7;
    int shl = n + s;
    while ((shl -= 8) > 0)
```
Here signed shl used and both n and s is unsigned. Code can be re-written to unsigned, but become less compact.
In some places int can be changed to unsigned, but no practical reason for it. And that places starts to interfere with places where it's needed by chain. It turns in lot of conversions.

**Comment by masterzorag** [comment]
I'm implementing your code to play s16le on a ps4 and seems facing some issue in decode_frame about sign (some values are wrong);
Also disabling SSE got completely different decoded values...
Have to dig more, since on linux x86_64 I got audio playing good;
Will try next tests with _-Wextra_, good point!

**Comment by lieff** [comment]
@masterzorag Is this toolchain public available? Can you post warnings log?

**Comment by masterzorag** [comment]
sorry @lieff for the late reply, but digging my code I solved implementing fine;
was just my fault, here it is: https://twitter.com/masterzorag/status/1142862398870773760
(basically, we are using Clang and standard tools to build elfs, but a custom loader is needed for execution)

**Comment by lieff** [comment]
Cool :)
