### ISSUE TITLE
Get information about frame offset

### ISSUE THREAD

**Issue by GregSlazinski** [lieff/minimp3#39]
Hi there,

Many thanks for the wonderful library.

Would be great if you could allow getting the frame offset in 'mp3dec_decode_frame'

My code changes:
```
typedef struct
{
-    int frame_bytes, channels, hz, layer, bitrate_kbps;
into->
+    int frame_offset, frame_size, channels, hz, layer, bitrate_kbps; // ESENTHEL CHANGED
} mp3dec_frame_info_t;
```

```
-            info->frame_bytes = i;
into
+            info->frame_offset = i; // ESENTHEL CHANGED
+           info->frame_size   = 0; // ESENTHEL CHANGED
```

and finally:
```
-    info->frame_bytes = i + frame_size;
into
+    info->frame_offset = i; // ESENTHEL CHANGED
+    info->frame_size   = frame_size; // ESENTHEL CHANGED
```

this allows to parse the MP3 first, remember each frame exact positions and sizes, so later when decoding, we can read only necesseary data, without having to rely on mp3d_find_frame iterating bytes, and possibly failing, because we've buffered only frame size, without the needed following data to properly detect the frame.

**Comment by lieff** [comment]
Hi) Thanks for the issue.
Is this really a problem? Most of time frame_offset should be zero, only garbage data skipped in this way. ID3 better handle separately anyway, because it can contain valid headers.
Can you provide case/file when it's useful?

**Comment by GregSlazinski** [comment]
Yes it is needed, if you first parse MP3 file to get exact length and info about all frames. in that situation you read ahead a lot of bytes at one time, I do 64k bytes and put that to decode function, all works well.

Once I've gathered all frames, then for actual decoding with PCM data, I read not 64k bytes to a temp buffer, but -only- the frame size bytes. And the first frame may fail, because the library works in a way, that if the actual frame data does not start at the beginning, but with an offset, then it does some extra validation checks, to see if after that frame, we've got another frame. But since I've read only enough data for 1 frame, then the library cannot do the extra validation checks, and fails.

So I've changed your library to return the offset, so when parsing the MP3 in the first step, I gather the precise frame start position and size, and when decoding, everything starts to work OK.

**Comment by lieff** [comment]
I understand first part about buffers problem. It's because minimp3 do not have internal combine buffer and it's recommended to always have 10 consecutive MP3 frames (~16KB) in buffer, documentations says about this. So, you must refill 64k buffer when it drops <16kb. On systems with mmap support there optimizations can be done: mmap block twice one after another (hardware ring buffer), or just mmap entire file.

What I can't understand - how passing offsets out helps you in your case. Correct mp3 file should be like this:
```
[id3v2 data][frame][frame]..[frame][id3v1 data]
```
If this case we get all offsets zero if we handle id3 properly.
Corrupted mp3 should be like this
```
[id3v2 data][frame][garbage bytes][frame]..[frame][id3v1 data]
```
If this case we get 0, num_garbage_bytes, 0, 0... offsets. Garbage should be relatively small, so optimization that we skip garbage in index and do not pass it to decode() almost useless. Also it makes index structure bigger for this rare corner case.
And this can't help you with buffering problem since rule you must have 10 consecutive MP3 frames (~16KB) while search for next frame for index building is still in effect for strong sync procedure. You can relax sync procedure though by lower MAX_FRAME_SYNC_MATCHES constant.

**Comment by GregSlazinski** [comment]
Hello,

I have 2 steps in my application:

1- parse entire MP3 without decoding the PCM data to build the index (list of all frames - their positions and sizes)
2-decode the MP3 file PCM data

In step number 2, I don't read 16kb bytes, but only read exactly one frame per a single decode step.

So because in the first step of parsing MP3 file, I've got a frame that includes garbage:
[garbage bytes][frame]
because no offset was provided.
Then decoding of this data fails, because:
data does not start with a frame, so it needs to do matching with a next frame:
https://github.com/lieff/minimp3/blob/master/minimp3.h#L1631
but in this data there is no next frame, so it fails completely.

After my code changes, of having the offsets,
instead of 
[garbage bytes][frame]
I have
[frame]
And everything starts to work completely, so yes the offsets are needed in this case.

**Comment by lieff** [comment]
Ah, now I see. You are trying to use decoder in MP4 mode i.e. exactly one non-free-format frame needed as input. I've already mention mp4 (re-)mux case.
I think how to handle this case without introducing complexity to decoder interface. Note that in this case you loose free-format support.
If you still want free-format support, you can build index at step 1 and start decode from any place in stream mode (I recommend just mmap file if it's not in compressed resource).

**Comment by lieff** [comment]
I still remember about this issue :)
I will try make remux sample with minimp4 sometime later.

**Comment by lieff** [comment]
Now frame offset passed to mp3dec_frame_info_t struct and file can be iterated using high-level mp3dec_iterate_* functions without decoder structure.
Sample will be tracked here https://github.com/lieff/minimp4/issues/12
