### ISSUE TITLE
How to remove extra delay samples?

### ISSUE THREAD

**Issue by Cocalus** [lieff/minimp3#63]
If I encode wav file (with 87,840,000 samples) to mp3 with Lame then decode it with minimp3, I get extra samples (now 87,841,152) . If I decode with lame or ffmpeg I get the original number of samples back. 

Notably when decoding with lame I get

```
input:  totalFile_t.mp3  (48 kHz, 2 channels, MPEG-1 Layer III)
output: totalFile_t.wav  (16 bit, Microsoft WAVE)
skipping initial 1105 samples (encoder+decoder delay)
skipping final 47 samples (encoder padding-decoder delay)
Frame# 76251/76251  128 kbps   MS
```

When adding the samples skipped from the delays (1105 + 47), it matches the length of minimp3. How can I calculate the number of samples to skip at the beginning and end to get minimp3 to match the length of the original (ie the output of lame and ffmpeg)?

**Comment by lieff** [comment]
Hello :) Thanks for the issue.

Do you use low level mp3dec_decode_frame function, or high-level mp3dec_load, mp3dec_iterate or mp3dec_ex_*?
Delay and padding information are stored by lame in vbr tag and handled only by high-level functions.
If you use high-level functions from current master and decoded length did nit match lame/ffmpeg then it's a bug and I need sample mp3 to fix it.

**Comment by Cocalus** [comment]
Thanks, the Rust language bindings I'm using is wrapping mp3dec_decode_frame. 

It looks like the minimp3 version it wraps is a bit old, I should be able to update that in my fork of the bindings. I might be able to switch it to a higher level API, but I'd like to do stream processing or at least avoid loading the entire mp3 file into memory if possible. Alternatively I can try to extended the Rust wrapper with VBR tag handling if I can figure out how the high level API manages it.

**Comment by lieff** [comment]
Yes, I think Rust wrapper needs extending as higher level API takes into shape. Streaming processing already works and tested a bit. With mp3dec_ex_open/mp3dec_ex_open_cb you can read/seek without load whole file into memory https://github.com/lieff/minimp3/blob/master/minimp3_test.c#L130 .
It's currently not reflected in documentation, and work still going on.

**Comment by Cocalus** [comment]
I can try to wrap the mp3dec_ex_open* if you don't expect the API to change with the ongoing work. If I never call mp3dec_ex_seek can the seek callback (io.seek in the test) be set to to NULL? The rust wrapper currently works with the Read trait (byte stream), which isn't seekable, so requiring seeking would forbid things like network streams and pipes which it current supports. I could probably extend the Rust wrapper to support seeking, but it's not a feature I currently have a use for.

**Comment by lieff** [comment]
Currently I do not expect mp3dec_ex_* API change, except error codes in case of failures.
Target for 1.0 release will be:

* Implement mp3dec_load_cb.
* Add windows wchar functions.
* Improve error codes.
* Implement usage of magic ring buffer to make less input buffer memmove in stream mode (if possible).
* Improve coverage of high-level API in test.
* Add seek capability in sample player.

**Comment by Cocalus** [comment]
Sounds like I could try wrapping the mp3dec_ex_* then.

Do I need to set the seek call back if I never use mp3dec_ex_seek?

I don't know if it's helpful but for the magic ring buffer there's a Rust implementation that works with all the major OSes, at https://github.com/gnzlbg/slice_deque/tree/master/src/mirrored. Since each OS has a different API, it might help figuring out the OS calls. It's rather complicated Rust code and I suspect there is an equivalent C library somewhere. Which would probably much easier to read if you're not familiar with Rust.

**Comment by lieff** [comment]
Yes, currently seek always needed in general case, because many API users wants to know how many samples in stream (dec.samples) at mp3dec_ex_open() time (to alloc memory, show length/progress etc). So file must be scanned to obtain it's length. Scan will be avoided if vbr tag is present (which contains length info), but stream still must be rewinded for read function when vbr tag readed.

Thanks for the link :) I already have working linux version, implementation looks same as mine. Macos code is useful since I haven't figured out how to make this macos yet. Windows looks borked, rust implementation tries bypass it by retrying: https://github.com/gnzlbg/slice_deque/blob/master/src/mirrored/winapi.rs#L78 but still no guarantee second map_view_of_file will work, so I think to disable it on windows.

**Comment by Cocalus** [comment]
I'm trying to wrap the callbacks but I'm not certain of their requirements.

For seek 
should I return errors with a non zero?

For read should 
Should I return errors as a negative value?
Should I always to fill size bytes, or just what it can get right now (ie read(2))
If there aren't size bytes remaining (for example eof) should it return an error or the just the number of bytes that are remaining.

**Comment by lieff** [comment]
I think use same behaviour as fread/fseek, but with minor difference:
For seek there no origin parameter, SEEK_SET always applied. A non-zero return value indicates an error.
For read same as for fread: total number of elements successfully read is returned. But ferror and feof is absent. Error indicated by (size_t)-1 or any value greater than requested size. Eof detected if return value != requested size, or it they truly equal at eof border - next read() should return zero.
So you can safely use fread/fseek in callback https://github.com/lieff/minimp3/blob/master/minimp3_test.c#L73 and it should be fine.

**Comment by Cocalus** [comment]
I think I got it working, I have my modified version of minimp3-rs at https://github.com/Cocalus/minimp3-rs I may try to do a PR with the original (I'm waiting on a new release of slice_deque). But it different enough they may not want to merge, assuming they take PRs.

I get an warning when compiling the newest version of minimp3. I guess the compiler thinks one of the function calls may modify io somehow (not that it does). Initialization to 0 should quiet the warning.

```
warning: minimp3/minimp3_ex.h: In function ‘mp3dec_load_cb’:
warning: minimp3/minimp3_ex.h:276:32: warning: ‘filled’ may be used uninitialized in this function [-Wmaybe-uninitialized]
warning:              if (!eof && filled - consumed < MINIMP3_BUF_SIZE)
```

Also through the mp3dec_ex_read functions what happens if the sample rate or number of channels change between frames?

**Comment by lieff** [comment]
>I get an warning when compiling the newest version of minimp3.

Hmm, gcc 8-9 do not produces any -Wmaybe-uninitialized warnings, what gcc version is it?

>Also through the mp3dec_ex_read functions what happens if the sample rate or number of channels change between frames?

Sample rate and layer change is invalid, mp3dec_load_* have guard code https://github.com/lieff/minimp3/blob/master/minimp3_ex.h#L377 .

Mono/stereo transition is possible, but very rarely used and enabled by MINIMP3_ALLOW_MONO_STEREO_TRANSITION define. It that case progress callback should decide what to do with the change.

For iterate functions all decided by user callback.

For mp3dec_ex_read there no good solution since there no any callbacks, I think to deny any transitions for it.

**Comment by Cocalus** [comment]
I get that warning when building through Rust's CC crate (https://github.com/alexcrichton/cc-rs) which should be using what ever cc is bound to on Linux, which in my case is gcc 4.8.4 (I know it's old). 

I can recreate the error with 
```
cc -O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall -Wextra -DMINIMP3_IMPLEMENTATION -c minimp3_test.c
```

I can add error checks to mp3dec_ex_read, if you want to return an error if the frame info changes.

**Comment by lieff** [comment]
May be warning worth fixing since gcc also is very old on macos. https://github.com/lieff/minimp3/commit/c5a14126a517f90ae9459645f2747f5d5247df93 should fix it.

>I can add error checks to mp3dec_ex_read, if you want to return an error if the frame info changes.

I've add MP3D_E_DECODE error to indicate this https://github.com/lieff/minimp3/commit/2ed89a6d88755846503bf1d69ab4482dec66f9f4 . For mp3dec_ex_read, when returned samples != requested samples, normal eof or error indicated in dec->last_error.

**Comment by Cocalus** [comment]
So for errors on mp3dec_ex
result < 0                   -- error that should be a MP3D_E_*
result > request         -- shouldn't happen so implies major issue (memory corruption)
result == request       -- ok
0 <= result < request -- EOF

Do I need to check dec->last_error if I check all mp3dec_ex_* calls for error codes? If so should I check it after each mp3dex_ex_* call?

**Comment by lieff** [comment]
Result is unsigned, so result < 0 is not possible. For result > request all is correct, shouldn't happen. For 0 <= result < request -- EOF (if dec->last_error==0) or dec->last_error error.

**Comment by Cocalus** [comment]
That should work, having mp3dec_ex_read return signed would also be an option.

**Comment by lieff** [comment]
Yes, it's a good option. Idea behind size_t that it's designed to hold address space for platform, so you can surely fill any buffer. If you make it signed - half address space is gone.

Currently it's not really a problem, because size of mp3d_sample_t is 2-4 bytes. But later, if we want support 8-bit mp3d_sample_t - it can be a problem.

Another problem is that ssize_t not so well and widely supported (msvc for example https://github.com/lieff/minimp4/blob/master/minimp4_test.c#L2).

**Comment by Cocalus** [comment]
I can use the last_error do I just need to check that after mp3dec_ex_read or after any call?

I forget about how much a pain ssize_t is.

**Comment by lieff** [comment]
Only for mp3dec_ex_read, mp3dec_ex_open/mp3dec_ex_seek already return error as result, so no need to set/check it in last_error.

**Comment by Cocalus** [comment]
I think my wrapper is finished now. I'll have to double check the API once Minimp3 1.0 comes out. Since 1.0 seems close I'll wait for that before I bug the other Rust bindings so they can either document the delay samples or handle them either with the mp3dex_ex_* api or by mimicking it's behavior.

Thanks for all your help.

**Comment by lieff** [comment]
Cool :) The release may not happen so fast (a month or so). To achieve full test coverage I need to make some non-standard vectors which trigger needed parts.

**Comment by mgeier** [comment]
In case someone is interested, I've started working on low-level Rust bindings for `minimp3_ex` there: https://github.com/mgeier/minimp3_ex-sys

The comments in this issue helped a lot!
