### ISSUE TITLE
Check for mono-stereo transition in mp3dec_ex_seek()?

### ISSUE THREAD

**Issue by mgeier** [lieff/minimp3#74]
If this is checked in `mp3dec_ex_read()`/`mp3dec_ex_read_frame()` ...

https://github.com/lieff/minimp3/blob/a50256232900935021e1a854418edcb7f8b4ae51/minimp3_ex.h#L902

... it should be checked when seeking as well, right?

Right now, we can seek from a mono to a stereo frame (or vice versa) without noticing.

Or am I missing something?

**Comment by lieff** [comment]
One possible application that comes in mind: app have one big mp3 stream and map which tells where mono or stereo samples located (may have even different real sample rate). For tracker music for example.

So assumed that if user enables MINIMP3_ALLOW_MONO_STEREO_TRANSITION than he knows what he is doing)
And this should be very rare case anyway.

**Comment by mgeier** [comment]
@lieff I think your comment is about #75, right?

**Comment by lieff** [comment]
Right. I think fix it by introducing another open flag for mp3dec_ex_open when MINIMP3_ALLOW_MONO_STEREO_TRANSITION enabled, and mp3dec_ex_read will fail and succeed on channel mismatch depending on this flag.

So both cases will be covered: when we no not want channel mismatch surprises and when we have external map and know what we are doing.

We can add this check to seek too, but this do not needed for MINIMP3_ALLOW_MONO_STEREO_TRANSITION/flag case, and currently target frame + MINIMP3_PREDECODE_FRAMES do not readed (io case) and not checked. So seek will be slightly slower and complicated. May be for such rare case seek+read fail will be enough.

**Comment by mgeier** [comment]
OK, if you do have *a priori* information about the MP3 file, keeping `MINIMP3_ALLOW_MONO_STEREO_TRANSITION` in the case mentioned in #75 might theoretically be useful.

So please feel free to close #75.

But what about this issue?

Assuming that `MINIMP3_ALLOW_MONO_STEREO_TRANSITION` is *unset*, we will get an error from `mp3dec_ex_read()` if we encounter a mono/stereo transition between two frames.

However, if we use `mp3dec_ex_seek()` to seek from a mono to a stereo frame (or vice versa), we will get no error!

**Comment by lieff** [comment]
Here solution I come up with: https://github.com/lieff/minimp3/commit/7bdfc8bd3cbb70e0b29556298c620587e38506f2 https://github.com/lieff/minimp3/commit/d86f4cbc9742c45b94cfb3e6cd86b951eeea7e5c

mp3dec_ex_read_frame how fills frame_info, so it can use it when transition enabled.
mp3dec_ex_read can use external map and enable/disable transition too.

As for seek we can get error on next frame anyway, not so big deal if application encounter error after zero samples instead of successfully decodes 10 samples and then gets an error. Of course it's not perfect if re do not get error directly on seek, but check requires to read additional frame which slows down normal case, so that`s a trade-off.
